import { DistributorDtlData } from "../../types/type";


export const dirtirbutorcolumns = [
    {
        field: "businessName",
        header: "Business Name",
        sorting: true,
        align: "left",
    },
    {
        field: "businessLicenseNo",
        header: "Business License No",
        sorting: true,
        align: "left",
    },
    {
        field: "businessContactDetails",
        header: "Business Contact Details",
        sorting: true,
        align: "left",
    },
    {
        field: "contactdetails",
        header: "Contact details",
        sorting: true,
        width: "20%",
        align: "left",
    },
    {

        field: "address",
        header: "Address",
        sorting: true,
        width: "25%",
        align: "left",
    },
    {
        field: "kYCVerification",
        header: "KYC Verification",
        sorting: true,
        width: "25%",
        align: "center",
    },
    {
        field: "status",
        header: "Status",
        sorting: true,
        align: "left",
    },

    {
        field: "CreatedDate",
        header: "Created Date",
        sorting: true,
        width: "15%",
        align: "center",
    },
    {
        field: "actions",
        header: "Action",
        sorting: false,
        width: "25%",
        align: "center",
    },
];
// Organization Table Row data 
export const dirtirbutorData = [
    {
        id: 1,
        businessName: "TechSolutions Pvt. Ltd.",
        businessId: "B-001",
        businessLicenseNo: "L45A-2024",
        businessContactDetails: "+919820012345",
        contactPerson: "Priya Sharma",
        email: "distributor1@example.com",
        address: "Mumbai, Maharashtra",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "15-01-2025",
    },
    {
        id: 2,
        businessName: "Gupta Retail Co.",
        businessId: "B-002",
        businessLicenseNo: "R89B-2023",
        businessContactDetails: "+919910023456",
        contactPerson: "Rohan Gupta",
        email: "distributor2@example.com",
        address: "Delhi, Delhi",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "22-02-2025",
    },
    {
        id: 3,
        businessName: "Reddy Logistics",
        businessId: "B-003",
        businessLicenseNo: "T12C-2024",
        businessContactDetails: "+919004034567",
        contactPerson: "Ananya Reddy",
        address: "Hyderabad, Telangana",
        email: "distributor3@example.com",
        kYCVerification: "verified",
        status: "Pending",
        CreatedDate: "05-03-2025",
    },
    {
        id: 4,
        businessName: "Singh & Associates",
        businessId: "B-004",
        businessLicenseNo: "F56D-2022",
        businessContactDetails: "+919892045678",
        contactPerson: "Vikram Singh",
        email: "distributor4@example.com",
        address: "Jaipur, Rajasthan",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "10-04-2025",
    },
    {
        id: 5,
        businessName: "Patel Exports",
        businessId: "B-005",
        businessLicenseNo: "E33A-2023",
        businessContactDetails: "+919821056789",
        contactPerson: "Sneha Patel",
        email: "distributor5@example.com",
        address: "Ahmedabad, Gujarat",
        kYCVerification: "verified",
        status: "Inactive",
        CreatedDate: "18-05-2025",
    },
    {
        id: 6,
        businessName: "Mehta Innovations",
        businessId: "B-006",
        businessLicenseNo: "L90B-2024",
        businessContactDetails: "+919876512345",
        contactPerson: "Arjun Mehta",
        email: "distributor6@example.com",
        address: "Pune, Maharashtra",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "25-06-2025",
    },
    {
        id: 7,
        businessName: "Iyer Catering Services",
        businessId: "B-007",
        businessLicenseNo: "C22F-2021",
        businessContactDetails: "+919988776655",
        contactPerson: "Kavita Iyer",
        email: "distributor6@example.com",
        address: "Chennai, Tamil Nadu",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "01-07-2025",
    },
    {
        id: 8,
        businessName: "Joshi Hardware",
        businessId: "B-008",
        businessLicenseNo: "H78G-2020",
        businessContactDetails: "+919123456789",
        contactPerson: "Manish Joshi",
        email: "distributor6@example.com",
        address: "Indore, Madhya Pradesh",
        kYCVerification: "verified",
        status: "Inactive",
        CreatedDate: "14-07-2025",
    },
    {
        id: 9,
        businessName: "Desai Fabrics",
        businessId: "B-009",
        businessLicenseNo: "F45H-2023",
        businessContactDetails: "+919819981998",
        contactPerson: "Pooja Desai",
        email: "distributor6@example.com",
        address: "Surat, Gujarat",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "20-08-2025",
    },
    {
        id: 10,
        businessName: "Kumar Financials",
        businessId: "B-010",
        businessLicenseNo: "F11J-2022",
        businessContactDetails: "+919619012345",
        contactPerson: "Rajesh Kumar",
        email: "distributor6@example.com",
        address: "Lucknow, Uttar Pradesh",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "30-08-2025",
    },
    {
        id: 11,
        businessName: "Rao Tech Labs",
        businessId: "B-011",
        businessLicenseNo: "T55K-2024",
        businessContactDetails: "+918879023456",
        contactPerson: "Sunita Rao",
        email: "distributor6@example.com",
        address: "Bangalore, Karnataka",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "12-09-2025",
    },
    {
        id: 12,
        businessName: "Verma Prints",
        businessId: "B-012",
        businessLicenseNo: "P88L-2023",
        businessContactDetails: "+919820034567",
        contactPerson: "Amit Verma",
        email: "distributor6@example.com",
        address: "Noida, Uttar Pradesh",
        kYCVerification: "verified",
        status: "Pending",
        CreatedDate: "15-09-2025",
    },
    {
        id: 13,
        businessName: "Krishnan Motors",
        businessId: "B-013",
        businessLicenseNo: "M33N-2021",
        businessContactDetails: "+919920045678",
        contactPerson: "Deepa Krishnan",
        address: "Kochi, Kerala",
        email: "distributor6@example.com",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "28-09-2025",
    },
    {
        id: 14,
        businessName: "Malhotra Group",
        businessId: "B-014",
        businessLicenseNo: "G44P-2020",
        businessContactDetails: "+919810056789",
        contactPerson: "Karan Malhotra",
        address: "Chandigarh, Punjab",
        email: "distributor6@example.com",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "01-10-2025",
    },
    {
        id: 15,
        businessName: "Agarwal Sweets",
        businessId: "B-015",
        businessLicenseNo: "S12Q-2019",
        businessContactDetails: "+919321067890",
        contactPerson: "Nisha Agarwal",
        address: "Agra, Uttar Pradesh",
        email: "distributor6@example.com",
        kYCVerification: "verified",
        status: "Active",
        CreatedDate: "10-10-2025",
    },
    {
        id: 16,
        businessName: "Ali Traders",
        businessId: "B-016",
        businessLicenseNo: "T77R-2022",
        businessContactDetails: "+919833078901",
        contactPerson: "Sameer Ali",
        address: "Kolkata, West Bengal",
        kYCVerification: "verified",
        email: "distributor6@example.com",
        status: "Active",
        CreatedDate: "15-10-2025",
    },
    {
        id: 17,
        businessName: "Nair Consultants",
        businessId: "B-017",
        businessLicenseNo: "C56S-2023",
        businessContactDetails: "+919845089012",
        contactPerson: "Divya Nair",
        address: "Bangalore, Karnataka",
        kYCVerification: "verified",
        email: "distributor6@example.com",
        status: "Active",
        CreatedDate: "22-10-2025",
    },
    {
        id: 18,
        businessName: "Bhat Industries",
        businessId: "B-018",
        businessLicenseNo: "I89T-2021",
        businessContactDetails: "+919004090123",
        contactPerson: "Harish Bhat",
        address: "Mangalore, Karnataka",
        kYCVerification: "verified",
        status: "Inactive",
        email: "distributor6@example.com",
        CreatedDate: "28-10-2025",
    },
    {
        id: 19,
        businessName: "Sen Enterprises",
        businessId: "B-019",
        businessLicenseNo: "E23U-2024",
        businessContactDetails: "+919830012345",
        contactPerson: "Meera Sen",
        address: "Kolkata, West Bengal",
        kYCVerification: "verified",
        status: "Pending",
        email: "distributor6@example.com",
        CreatedDate: "05-11-2025",
    },
    {
        id: 20,
        businessName: "Jha Services",
        businessId: "B-020",
        businessLicenseNo: "S76V-2023",
        businessContactDetails: "+919560023456",
        contactPerson: "Prakash Jha",
        address: "Patna, Bihar",
        kYCVerification: "verified",
        status: "Active",
        email: "distributor6@example.com",
        CreatedDate: "14-11-2025",
    },
];

export const dirtirbutorKYCcolumns = [
    {
        field: "businessName",
        header: "Business Name",
        sorting: true,
        align: "left",
    },
    {
        field: "businessLicenseNo",
        header: "Business License No",
        sorting: true,
        align: "left",
    },
    {
        field: "businessContactDetails",
        header: "Business Contact Details",
        sorting: true,
        align: "left",
    },
    {
        field: "contactdetails",
        header: "Contact details",
        sorting: true,
        width: "20%",
        align: "left",
    },
    {

        field: "address",
        header: "Address",
        sorting: true,
        width: "25%",
        align: "left",
    },
    {
        field: "kYCVerification",
        header: "KYC Verification",
        sorting: true,
        width: "25%",
        align: "center",
    },

    {
        field: "CreatedDate",
        header: "Created Date",
        sorting: true,
        width: "15%",
        align: "center",
    },
    {
        field: "actions",
        header: "Action",
        sorting: false,
        width: "25%",
        align: "center",
    },
];

export const dirtirbutorKYCData = [
    {
        id: 1,
        businessName: "TechSolutions Pvt. Ltd.",
        businessId: "B-001",
        businessLicenseNo: "L45A-2024",
        businessContactDetails: "+919820012345",
        contactPerson: "Priya Sharma",
        email: "distributor1@example.com",
        address: "Mumbai, Maharashtra",
        kYCVerification: "pending",
        status: "Active",
        CreatedDate: "15-01-2025",
    },
    {
        id: 2,
        businessName: "Gupta Retail Co.",
        businessId: "B-002",
        businessLicenseNo: "R89B-2023",
        businessContactDetails: "+919910023456",
        contactPerson: "Rohan Gupta",
        email: "distributor2@example.com",
        address: "Delhi, Delhi",
        kYCVerification: "pending",
        status: "Active",
        CreatedDate: "22-02-2025",
    },
    {
        id: 3,
        businessName: "Reddy Logistics",
        businessId: "B-003",
        businessLicenseNo: "T12C-2024",
        businessContactDetails: "+919004034567",
        contactPerson: "Ananya Reddy",
        address: "Hyderabad, Telangana",
        email: "distributor3@example.com",
        kYCVerification: "failed",
        status: "Pending",
        CreatedDate: "05-03-2025",
    },
    {
        id: 4,
        businessName: "Singh & Associates",
        businessId: "B-004",
        businessLicenseNo: "F56D-2022",
        businessContactDetails: "+919892045678",
        contactPerson: "Vikram Singh",
        email: "distributor4@example.com",
        address: "Jaipur, Rajasthan",
        kYCVerification: "failed",
        status: "Active",
        CreatedDate: "10-04-2025",
    },
    {
        id: 5,
        businessName: "Patel Exports",
        businessId: "B-005",
        businessLicenseNo: "E33A-2023",
        businessContactDetails: "+919821056789",
        contactPerson: "Sneha Patel",
        email: "distributor5@example.com",
        address: "Ahmedabad, Gujarat",
        kYCVerification: "pending",
        status: "Inactive",
        CreatedDate: "18-05-2025",
    },
    {
        id: 6,
        businessName: "Mehta Innovations",
        businessId: "B-006",
        businessLicenseNo: "L90B-2024",
        businessContactDetails: "+919876512345",
        contactPerson: "Arjun Mehta",
        email: "distributor6@example.com",
        address: "Pune, Maharashtra",
        kYCVerification: "failed",
        status: "Active",
        CreatedDate: "25-06-2025",
    },
    {
        id: 7,
        businessName: "Iyer Catering Services",
        businessId: "B-007",
        businessLicenseNo: "C22F-2021",
        businessContactDetails: "+919988776655",
        contactPerson: "Kavita Iyer",
        email: "distributor6@example.com",
        address: "Chennai, Tamil Nadu",
        kYCVerification: "pending",
        status: "Active",
        CreatedDate: "01-07-2025",
    },
    {
        id: 8,
        businessName: "Joshi Hardware",
        businessId: "B-008",
        businessLicenseNo: "H78G-2020",
        businessContactDetails: "+919123456789",
        contactPerson: "Manish Joshi",
        email: "distributor6@example.com",
        address: "Indore, Madhya Pradesh",
        kYCVerification: "failed",
        status: "Inactive",
        CreatedDate: "14-07-2025",
    },
    {
        id: 9,
        businessName: "Desai Fabrics",
        businessId: "B-009",
        businessLicenseNo: "F45H-2023",
        businessContactDetails: "+919819981998",
        contactPerson: "Pooja Desai",
        email: "distributor6@example.com",
        address: "Surat, Gujarat",
        kYCVerification: "failed",
        status: "Active",
        CreatedDate: "20-08-2025",
    },
    {
        id: 10,
        businessName: "Kumar Financials",
        businessId: "B-010",
        businessLicenseNo: "F11J-2022",
        businessContactDetails: "+919619012345",
        contactPerson: "Rajesh Kumar",
        email: "distributor6@example.com",
        address: "Lucknow, Uttar Pradesh",
        kYCVerification: "pending",
        status: "Active",
        CreatedDate: "30-08-2025",
    },
    {
        id: 11,
        businessName: "Rao Tech Labs",
        businessId: "B-011",
        businessLicenseNo: "T55K-2024",
        businessContactDetails: "+918879023456",
        contactPerson: "Sunita Rao",
        email: "distributor6@example.com",
        address: "Bangalore, Karnataka",
        kYCVerification: "pending",
        status: "Active",
        CreatedDate: "12-09-2025",
    },
    {
        id: 12,
        businessName: "Verma Prints",
        businessId: "B-012",
        businessLicenseNo: "P88L-2023",
        businessContactDetails: "+919820034567",
        contactPerson: "Amit Verma",
        email: "distributor6@example.com",
        address: "Noida, Uttar Pradesh",
        kYCVerification: "failed",
        status: "Pending",
        CreatedDate: "15-09-2025",
    },
    {
        id: 13,
        businessName: "Krishnan Motors",
        businessId: "B-013",
        businessLicenseNo: "M33N-2021",
        businessContactDetails: "+919920045678",
        contactPerson: "Deepa Krishnan",
        address: "Kochi, Kerala",
        email: "distributor6@example.com",
        kYCVerification: "failed",
        status: "Active",
        CreatedDate: "28-09-2025",
    },
    {
        id: 14,
        businessName: "Malhotra Group",
        businessId: "B-014",
        businessLicenseNo: "G44P-2020",
        businessContactDetails: "+919810056789",
        contactPerson: "Karan Malhotra",
        address: "Chandigarh, Punjab",
        email: "distributor6@example.com",
        kYCVerification: "pending",
        status: "Active",
        CreatedDate: "01-10-2025",
    },
    {
        id: 15,
        businessName: "Agarwal Sweets",
        businessId: "B-015",
        businessLicenseNo: "S12Q-2019",
        businessContactDetails: "+919321067890",
        contactPerson: "Nisha Agarwal",
        address: "Agra, Uttar Pradesh",
        email: "distributor6@example.com",
        kYCVerification: "failed",
        status: "Active",
        CreatedDate: "10-10-2025",
    },
    {
        id: 16,
        businessName: "Ali Traders",
        businessId: "B-016",
        businessLicenseNo: "T77R-2022",
        businessContactDetails: "+919833078901",
        contactPerson: "Sameer Ali",
        address: "Kolkata, West Bengal",
        kYCVerification: "pending",
        email: "distributor6@example.com",
        status: "Active",
        CreatedDate: "15-10-2025",
    },
    {
        id: 17,
        businessName: "Nair Consultants",
        businessId: "B-017",
        businessLicenseNo: "C56S-2023",
        businessContactDetails: "+919845089012",
        contactPerson: "Divya Nair",
        address: "Bangalore, Karnataka",
        kYCVerification: "failed",
        email: "distributor6@example.com",
        status: "Active",
        CreatedDate: "22-10-2025",
    },
    {
        id: 18,
        businessName: "Bhat Industries",
        businessId: "B-018",
        businessLicenseNo: "I89T-2021",
        businessContactDetails: "+919004090123",
        contactPerson: "Harish Bhat",
        address: "Mangalore, Karnataka",
        kYCVerification: "failed",
        status: "Inactive",
        email: "distributor6@example.com",
        CreatedDate: "28-10-2025",
    },
    {
        id: 19,
        businessName: "Sen Enterprises",
        businessId: "B-019",
        businessLicenseNo: "E23U-2024",
        businessContactDetails: "+919830012345",
        contactPerson: "Meera Sen",
        address: "Kolkata, West Bengal",
        kYCVerification: "pending",
        status: "Pending",
        email: "distributor6@example.com",
        CreatedDate: "05-11-2025",
    },
    {
        id: 20,
        businessName: "Jha Services",
        businessId: "B-020",
        businessLicenseNo: "S76V-2023",
        businessContactDetails: "+919560023456",
        contactPerson: "Prakash Jha",
        address: "Patna, Bihar",
        kYCVerification: "pending",
        status: "Active",
        email: "distributor6@example.com",
        CreatedDate: "14-11-2025",
    },
];

export const kycColumns = [
    {
        field: "documentName",
        header: "DocumentName",
        sorting: true,
        align: "left",
    },
    {
        field: "image",
        header: "Image",
        sorting: true,
        align: "left",
    },
    {
        field: "status",
        header: "Status",
        sorting: true,
        align: "left",
    }
]


export const data: DistributorDtlData =
{
    id: "DIST-001",
    profile: {
        distributorName: "ABCD DistibutorPro",
        companyType: "Private Limited Company",
        distributorCode: "STS001",
        avatar: "path/to/image.png"
    },
    meta: {
        createdDate: "12-02-2025",
        createdBy: "Tilak Kumar"
    },
    personalInfo: {
        fullName: "Praveen suthar",
        mobileNumber: "+91-5435643456",
        altMobileNumber: "+91-5435643456",
        aadhaarNo: "1232-4325-4325",
        panNo: "1232-4325-4325",
        emailId: "Prateek5463@gmail.com"
    },
    businessInfo: {
        businessName: "ABCD Distirbutorpro",
        gstNumber: "BLN-IND-2025-123456",
        licenseNumber: "BLN-IND-2025-123456",
        emailId: "britirbutor5463@gmail.com",
        mobileNumber: "91-986565454"
    },
    otherInfo: {
        bankDetails: {
            accountHolderName: "ABCD Distirbutorpro",
            bankName: "SBI bank",
            accountNumber: "BLN-IND-2025-123456",
            ifscCode: "KKBK0000123",
            upiId: "britirbutor5463@UPI.com"
        },
        referenceContact: {
            personName: "Praveen suthar",
            contactNumber: "91-65756767575",
            address: "Sirohi rajasthan"
        },
        primaryAddress: {
            fullAddress: "Sirohi main road village rampura"
        }
    },
    document: [
        {
            name: "Aadhaar Front",
            img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaNPQcQ8y9uflgKy0BC0F6ue6qU3MTVwze0w8XhbfWkiKjh1vf4qTrqL9xXcNluV1z6vE&usqp=CAU",
        },
        {
            name: "Aadhaar Back",
            img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaNPQcQ8y9uflgKy0BC0F6ue6qU3MTVwze0w8XhbfWkiKjh1vf4qTrqL9xXcNluV1z6vE&usqp=CAU",
        },
        {
            name: "PAN Card",
            img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiZl46uvn7hV85gs9sCFeDzIPAvB8liHElqg&s",
        },
    ],
    businessName: "",
    businessId: "",
    businessLicenseNo: "",
    businessContactDetails: "",
    contactPerson: "",
    address: "",
    kYCVerification: "",
    status: "",
    CreatedDate: ""
}

